### ISSUE TITLE
Any plans to merge in the `tweak` branch into master? 

### ISSUE THREAD

**Issue by joesaby** [aboutsip/sipstack#6]
Jonas,
Any plans to merge in the `tweak` branch into master? 

Cheers, Jose

**Comment by jonbo372** [comment]
Hey Jose,

Wow, I had completely forgotten about that branch. Currently no, no plans. I don't even remember what I did! :-) I'm currently adding some new stuff to pkts.io so not sure when I'll get back to sipstack.io.

**Comment by joesaby** [comment]
Hi Jonas
Did you pull down the tweak branch? There was a lot of useful patterns in
there? Wondering if you could resurrect that branch?

Thanks
Jose

**Comment by jonbo372** [comment]
Hey,

Probably not by myself in the near future, regular work is taking up all my
time currently. I do have another private branch that is a better version
of that branch though, and one I'd like to get out, if nothing else to get
some feedback on but, in the same way, I'm just strapped for time.

Curious though, because requests like yours inspire me and makes me want to
work on it again, what patterns on the tweek branch do you like? Anything
in particular? Anything that you don't like? There's not a lot SIP
developers out there so any input at all is greatly appreciated!

/Jonas

**Comment by joesaby** [comment]
Hi Jonas
Thanks for your reply.

Only after I sent you the email I realised the branch I was referring to
was on https://github.com/ajansson76 's fork. So I eventually found what I
was looking for.

So in the `*tweek*` branch, there was a lot of code around an enhanced
registrar, proxy, good patterns around b2b & sipstack was much more evolved
there (as I briefly went through it).

If it inspires you any more, we have started using *pkts* & *sipstack* in
our functional testing (basic reg, call) for our SBC & also to build up few
mock core elements. So not used in production!

Nothing too fancy, but few of us have started liking the library because of
its simplicity & very java8+ which is unlike other JAVA sip libraries.
There is very little in *sipstack* at the moment, but some of the examples
you had was perfect to get us bootstrapped. The *pkts* part of SIP is not
perfect, but good news is its quite extensible.

No major enhancements we can think of now other than few fixes on the TCP
Streaming part (*pkts* lib), if there are enhancements, we will start
contributing back. At Cisco you have to get a small blessing to start
contributing back to an opensource project, so thats the only resistance,
otherwise, we'd start contributing back.

Cheers
Jose
